### PR TITLE
The Python DDNS(Dynamic DNS) cli for ArvanCloud. [WIP] 

### PR DESCRIPTION
**Pull request by arastu**

### CODE REVIEW

**Comment by 3a8r** [comment]
I merge the pull request.
please add:
1- Option to get system interface name(if there is multiple interfaces)
2- Option to get IP directly from user(in case the script run from another system)

**Comment by arastu** [comment]
thanks @smesgary, On it

**Comment by arastu** [comment]
@smesgary is it possible to invite me as a collaborator to the repo?

**Comment by 3a8r** [comment]
Done.

**Pull request merged**
