### PR TITLE
bash file added

### PR DESCRIPTION
**Pull request by pooriaghaedi**

### CODE REVIEW

**Comment by 3a8r** [comment]
No documentation and example

**Comment by pooriaghaedi** [comment]
Example Added

**Comment by 3a8r** [comment]
Please Add the feature of getting IP directly from command line beside check the server IP

**Comment by 3a8r** [comment]
which interface of server? the server may have multiple network interfaces and so multiple IPs

**Comment by pooriaghaedi** [comment]
Getting IP directly added, It doesn't check for Interface's IP address. It gets the public ip address from internet.

**Comment by 3a8r** [comment]
Hi. thanks.
I will merge the pull request as a bash script beside python script from another pr.
please organize the project in next pr.

**Pull request merged**
